homepage_item :'V2Web::Standard', :getter => 'sites'
homepage_item :'V2Web::Section', :getter => 'web_sections'
homepage_item :'V2Web::Box', :getter => 'boxes'
homepage_item :'V2Web::Table'
homepage_item :'V2Web::Text'
# homepage_item :'V2Web::Example'
# homepage_item :'V2Web::Note'
homepage_item :'V2Web::Code'
homepage_item :'V2Web::Figure'
homepage_item :'V2Web::List'
homepage_item :'HL7::V2::Event', :getter => 'events'
homepage_item :'HL7::V2::Message', :getter => 'message_definitions'
homepage_item :'HL7::V2::SegmentDefinition', :getter => 'segment_definitions'
homepage_item :'HL7::V2::DataType', :getter => 'data_types'
homepage_item :'HL7::V2::DataElement', :getter => 'data_elements'
homepage_item :'HL7::V2::Component', :getter => 'components'
homepage_item :'HL7::Vocab::CodeSystem', :getter => 'code_systems'
homepage_item :'HL7::Vocab::ConceptDomain', :getter => 'concept_domains'
