load File.expand_path('procs.rb', __dir__)

organizer(:Details, Home) {
  html(:label => 'hl7_section', :html => V2Web::HL7_SECTION_LABEL)
  # html(:label => 'hl7v2link', :html => V2Web::HL7_LINK_LABEL)
  view_ref(:Summary, 'events', :label => 'Events')
  view_ref(:Summary, 'message_definitions', :label => 'Message Definitions')
  view_ref(:Summary, 'segment_definitions', :label => 'Segment Definitions')
  view_ref(:Summary, 'data_elements', :label => 'Data Elements')
  view_ref(:Summary, 'data_types', :label => 'Data Type Definitions')
  view_ref(:Summary, 'components', :label => 'Data Type Components')
  view_ref(:Summary, 'code_systems', :label => 'Code Systems')
  view_ref(:Summary, 'concept_domains', :label => 'Concept Domains')
  html(:label => 'websites_section', :html => V2Web::WEBSITES_LABEL)
  view_ref(:Summary, 'sites',      :label => 'Website Specifications')
  view_ref(:Summary, 'web_sections',   :label => 'Sections')
  view_ref(:Summary, 'boxes',      :label => 'Boxes')
  view_ref(:Summary, 'figures',    :label => 'Figures')
  view_ref(:Summary, 'tables',     :label => 'Tables')
  view_ref(:Summary, 'lists',      :label => 'Lists')
  view_ref(:Summary, 'codes',      :label => 'Code Snippets')
  view_ref(:Summary, 'texts',      :label => 'Text Sections')  
  # html(:label => 'fhir_link', :html => V2Web::FHIR_LINK_LABEL)
  # view_ref(:Summary, 'compositions',            :label => 'Composition Resources')
  # view_ref(:Summary, 'fhir_sections',                :label => 'Sections')
  # view_ref(:Summary, 'narratives',              :label => 'Narratives')
  # reorder(:to_beginning => true)
  # reorder('fhir_link', 'compositions', 'sections', 'narratives', :to_end => true)
  order('hl7_section', 'events', 'message_definitions', 'segment_definitions', 'data_elements', 'data_types', 'components', 'code_systems', 'concept_domains', 'websites_section', 'sites', 'web_sections', 'boxes', 'figures', 'tables' , 'lists', 'codes', 'texts', :to_beginning => true)
  
}
